#!/bin/sh

DIR=$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd)

if [ -n "$NVIM_FLAKE" ]; then
	NVIM_BIN="nix run $DIR --"
else
	NVIM_BIN=nvim
fi
export NVIM_BIN
"$DIR"/nvim_cold_reload/nvim_cold_reload.sh "$@"
