return {
  'nvim-treesitter/nvim-treesitter',
  lazy = false,
  branch = "main",
  dependencies = {
    'nvim-treesitter/nvim-treesitter-textobjects',
  },
  config = function()
    require('nvim-treesitter').install({
      "css",
      "diff",
      "dockerfile",
      "fsharp",
      "gitcommit",
      "gitignore",
      "git_rebase",
      "go",
      "gomod",
      "gosum",
      "html",
      "java",
      "javascript",
      "jq",
      "json",
      "kotlin",
      "nix",
      "python",
      "regex",
      "rust",
      "toml",
      "xml",
      "yaml",
    }):wait(300000)
  end,
}
